# Input
input:
  trait: "T2D"
  gwas_raw: "/storage/yangjianLab/sharedata/GWAS_summary/01_Public/01_cojo/DIAMANTE_EUR_T2D_2022_NG.txt"
  gwas: "/storage/yangjianLab/sharedata/GWAS_summary/01_Public/01_cojo/DIAMANTE_EUR_T2D_2022_NG.txt"
  output: "/storage/yangjianLab/guoyazhou/GAMMA_git_data"
  user_e2g_list: "/storage/yangjianLab/guoyazhou/GAMMA_github/MAGIC/scripts/user_xQTL_input/user_e2g_list.txt"
  user_xQTL_list: "/storage/yangjianLab/guoyazhou/GAMMA_github/MAGIC/scripts/user_xQTL_input/user_xQTL_list.txt"
  user_xQTL_link_consensus: "/storage/yangjianLab/guoyazhou/GAMMA_git_data/MAGIC/user_xQTL/user_xQTL_consensus.link.txt"
script:
  work_path: "/storage/yangjianLab/guoyazhou/GAMMA_github/MAGIC/scripts"
  path: "/storage/yangjianLab/guoyazhou/GAMMA_github/MAGIC/scripts"
software:
  smr: "/storage/yangjianLab/wangkai/SMR/build/Release/smr"
  plink1_9: "/storage/yangjianLab/guoyazhou/software/plink/plink1.90beta/plink_1.90_beta"
  plink2: "/storage/yangjianLab/guoyazhou/software/plink/plink2.00alpha/plink2"
  bedtools: "/storage/yangjianLab/guoyazhou/anaconda3/bin/bedtools"
  epi_to_bed: "/storage/yangjianLab/qiting/SMR_Cauchy/xMAGIC_pipeline/code/epi_2_bed.R"
  get_concensus_link: "/storage/yangjianLab/guoyazhou/GAMMA_github/MAGIC/scripts/user_xQTL_input/step0_get_consensus_link.R"
environment:
  R_421: "Drugsets_py385"
reference:
  reference_bfile: "/storage/yangjianLab/guoyazhou/data/Reference/UKB_Reference_genotype/genotype_10k_hg38/BED_ukbEUR_imp_v3_INFO0.8_maf0.01_mind0.05_geno0.05_hwe1e6_10K_hg38"
  reference_bld: "/storage/yangjianLab/guoyazhou/project_new/project_SMR_visualizaiton/script/test_script/run_time_test/bld_format/BED_ukbEUR_imp_v3_INFO0.8_maf0.01_mind0.05_geno0.05_hwe1e6_10K_hg38_4Mb"
  reference_all_bim: "/storage/yangjianLab/sharedata/LD_reference/UKB/genotype_10K/BED_ukbEUR_imp_v3_INFO0.8_maf0.01_mind0.05_geno0.05_hwe1e6_10K_hg38_chrALL.bim"
gene:
  gencode: "/storage/yangjianLab/qiting/data/annotation/gencode/gencode.v40.GRCh38.gene.annotation.bed"
magic:
  QTL_list_lite_new: "/storage/yangjianLab/guoyazhou/GAMMA_github/gamma-script/scripts/L2G/MAGIC_data/QTL_magic_published/MAGIC_published_xQTL.txt"
  QTL_list_lite_old: "/storage/yangjianLab/guoyazhou/GAMMA_github/gamma-script/scripts/L2G/MAGIC_data/QTL_lite_besd/QTL_list_lite.txt"
  QTL_list: "/storage/yangjianLab/guoyazhou/GAMMA_github/MAGIC/data/QTL_data/QTL_list.txt"
  QTL_name_list: "/storage/yangjianLab/guoyazhou/GAMMA_github/gamma-script/scripts/L2G/MAGIC_data/QTL_magic_published/MAGIC_published_xQTL_name_list.txt"
  R_functions: "/storage/yangjianLab/guoyazhou/GAMMA_github/MAGIC/scripts/R_functions/magic_functions.r"
  CpG_link: "/storage/yangjianLab/qiting/SMR_Cauchy/link/consensus/CpG_consensus_all.link"
  hQTL_link: "/storage/yangjianLab/qiting/SMR_Cauchy/link/consensus/hQTL_consensus_all.link"
  caQTL_link: "/storage/yangjianLab/qiting/SMR_Cauchy/link/consensus/caQTL_consensus_all.link"
link_annotation:
  genome_hg38: "/storage/yangjianLab/qiting/SMR_Cauchy/xMAGIC_pipeline/input/GRCh38.genome"
  ABC: "/storage/yangjianLab/qiting/SMR_Cauchy/xMAGIC_pipeline/epimark-to-gene/ABC0.015_ProteinCoding_GRCh38_CHRALL.bed"
  EpiMap: "/storage/yangjianLab/qiting/SMR_Cauchy/xMAGIC_pipeline/epimark-to-gene/EpiMap_links_by_group.CHRALL_GRCh38.bed"
  RoadMap: "/storage/yangjianLab/qiting/SMR_Cauchy/xMAGIC_pipeline/epimark-to-gene/Roadmap_links_ProteinCoding_GRCh38.bed"
  PCHiC: "/storage/yangjianLab/qiting/SMR_Cauchy/xMAGIC_pipeline/epimark-to-gene/PCHiC_Combined_ProteinCoding_GRCh38.bed"
  Promoter: "/storage/yangjianLab/qiting/SMR_Cauchy/xMAGIC_pipeline/epimark-to-gene/gencode.v40.PromoterTSS1kb.GRCh38.bed"
  closestTSS: "/storage/yangjianLab/qiting/SMR_Cauchy/xMAGIC_pipeline/epimark-to-gene/gencode.v40.closestTSS.GRCh38.bed"
R_dependencies:
  r_version: "4.2.1"
  r_packages:
    data.table: "1.15.4"
    stringr: "1.5.1"
    dplyr: "1.1.4"
    qvalue: "2.30.0"
    tidyverse: "2.0.0"
    GenomicRanges: "1.50.2"
    regioneR: "1.30.0"
    Repitools: "1.44.0"
    mgcv: "1.8.40"
